# Generated by Django 3.2.7 on 2021-10-02 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('author', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2021, 10, 2, 4, 58, 30, 867241, tzinfo=utc))),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=50)),
                ('context', models.CharField(max_length=1000)),
                ('commets_time', models.DateTimeField(default=datetime.datetime(2021, 10, 2, 4, 58, 30, 868233, tzinfo=utc))),
                ('approved_comments', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='blog.post')),
            ],
        ),
    ]
