# Generated by Django 3.2.6 on 2021-09-25 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 5, 42, 49, 459059, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 5, 42, 49, 458061, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='publishTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
