# Generated by Django 3.2.7 on 2021-10-02 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211002_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='context',
            field=models.TextField(default='FUck'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commets_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 5, 34, 52, 380779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 5, 34, 52, 380779, tzinfo=utc)),
        ),
    ]
