# Generated by Django 3.1.7 on 2021-10-23 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20211023_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_time',
            new_name='published_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commets_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 5, 8, 31, 278762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 5, 8, 31, 278762, tzinfo=utc)),
        ),
    ]
