# Generated by Django 3.1.7 on 2021-10-30 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20211023_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commets_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 4, 40, 32, 659419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='context',
            field=models.TextField(default='Type your Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 4, 40, 32, 659419, tzinfo=utc)),
        ),
    ]
