# Generated by Django 3.1.7 on 2021-11-13 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20211113_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commets_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 5, 22, 49, 37729, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 5, 22, 49, 36732, tzinfo=utc)),
        ),
    ]
