# Generated by Django 3.1.7 on 2021-12-04 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20211204_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commets_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 5, 15, 41, 836821, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 5, 15, 41, 836821, tzinfo=utc)),
        ),
    ]
